%% First, project template to subject
session_dir = '/data/jag/MELA/HERO_mxs1/040816';
subject_name =  'HERO_mxs1_MaxMel';
SUBJECTS_DIR = '/data/jag/MELA/freesurfer_subjects';

 hemis = {...
        'lh'...
        'rh'...
        };

templ2subject (session_dir, subject_name, SUBJECTS_DIR, hemis)



%% Set up parameters
session_dir = '/data/jag/MELA/HERO_mxs1/040816';
subject_name =  'HERO_mxs1_MaxMel';
subj_name = 'HERO_mxs1';
dropbox_dir = '/Users/giulia/Dropbox (Aguirre-Brainard Lab)/MELA_analysis/MelanopsinMR/MelPulses_400%/HERO_mxs1/040616';
SUBJECTS_DIR = '/data/jag/MELA/freesurfer_subjects';
copeNames = {...
    'Sec00' ...
    'Sec01' ...
    'Sec02' ...
    'Sec03' ...
    'Sec04' ...
    'Sec05' ...
    'Sec06' ...
    'Sec07' ...
    'Sec08' ...
    'Sec09' ...
    'Sec10' ...
    'Sec11' ...
    'Sec12' ...
    'Sec13' ...
    };
hemis = {...
    'mh'...
    'lh'...
    'rh'...
    };
ROIs = {...
    'LGN'...
    'V2andV3'...
    'V1' ...
    %         'V1all'...
    %         'V1low'...
    %         'V1mid'...
    %         'V1high'...
    };

funcs = {...
    'FIR_raw' ...
    % 'FIR_5mm'...
    };
funcNames = {...
    'FIR.raw' ...
    % 'FIR.5mm'...
    };

Conditions = {'MaxMelPulse'};
Runs = {[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]};
%% PSC COPES
for hh = 1:length(hemis)
    hemi = hemis{hh};
    
    for jj = 1:length(ROIs)
        ROI = ROIs{jj};
        % Get ROIind
        areas = load_nifti(fullfile(session_dir,[hemi '.areas.vol.nii.gz'])); % both hemis
        ecc = load_nifti(fullfile(session_dir,[hemi '.ecc.vol.nii.gz'])); % both hemis
        switch ROI
            case 'V1all'
                ROIind = find(abs(areas.vol)==1); % all of V1
            case 'V1low'
                ROIind = find(abs(areas.vol)==1 & ecc.vol<=5);
            case 'V1mid'
                ROIind = find(abs(areas.vol)==1 & (ecc.vol>5 & ecc.vol<=15));
            case 'V1high'
                ROIind = find(abs(areas.vol)==1 & (ecc.vol>15 & ecc.vol<=40));
            case 'V2andV3'
                ROIind = find(abs(areas.vol)==2 | abs(areas.vol)==3);
            case 'LGN'
                if strcmp(hemi,'mh')
                    lgn_rh = load_nifti(fullfile(session_dir, 'rh.LGN.prob.nii.gz'));
                    lgn_lh = load_nifti(fullfile(session_dir, 'lh.LGN.prob.nii.gz'));
                    ROIind = find((lgn_rh.vol)>=25 | (lgn_lh.vol)>=25);
                else
                    lgn = load_nifti(fullfile(session_dir, [hemi '.LGN.prob.nii.gz']));
                    ROIind = find((lgn.vol)>=25);
                end
            case 'V1'
                ROIind = find(abs(areas.vol)==1 & (ecc.vol>5 & ecc.vol<=30));
        end
        
        
        % Get means
        for ff = 1:length(funcs)
            func = funcs{ff};
            funcName = funcNames{ff};
            for i = 1:length(Conditions)
                condName = Conditions{i};
                runNums = Runs{i};
                psc_cope(session_dir,subject_name,runNums,func,ROIind, copeNames);
                
            end
        end
    end
end



%% Plot the FIR
FIR_assemble(session_dir, subject_name, subj_name, dropbox_dir, SUBJECTS_DIR, ...
    copeNames, hemis, ROIs, funcs, funcNames, Conditions, Runs);