qsub -l h_vmem=50.2G,s_vmem=50G -e /data/jag/MELA/MelanopsinMR/logs -o /data/jag/MELA/MelanopsinMR/logs /data/jag/MELA/MelanopsinMR/fixSubsASB-01.sh
qsub -l h_vmem=50.2G,s_vmem=50G -e /data/jag/MELA/MelanopsinMR/logs -o /data/jag/MELA/MelanopsinMR/logs /data/jag/MELA/MelanopsinMR/fixSubsASB-02.sh
qsub -l h_vmem=50.2G,s_vmem=50G -e /data/jag/MELA/MelanopsinMR/logs -o /data/jag/MELA/MelanopsinMR/logs /data/jag/MELA/MelanopsinMR/fixSubsASB-03.sh
qsub -l h_vmem=50.2G,s_vmem=50G -e /data/jag/MELA/MelanopsinMR/logs -o /data/jag/MELA/MelanopsinMR/logs /data/jag/MELA/MelanopsinMR/fixSubsASB-04.sh
qsub -l h_vmem=50.2G,s_vmem=50G -e /data/jag/MELA/MelanopsinMR/logs -o /data/jag/MELA/MelanopsinMR/logs /data/jag/MELA/MelanopsinMR/fixSubsASB-05.sh
qsub -l h_vmem=50.2G,s_vmem=50G -e /data/jag/MELA/MelanopsinMR/logs -o /data/jag/MELA/MelanopsinMR/logs /data/jag/MELA/MelanopsinMR/fixSubsASO-01.sh
qsub -l h_vmem=50.2G,s_vmem=50G -e /data/jag/MELA/MelanopsinMR/logs -o /data/jag/MELA/MelanopsinMR/logs /data/jag/MELA/MelanopsinMR/fixSubsASO-02.sh
qsub -l h_vmem=50.2G,s_vmem=50G -e /data/jag/MELA/MelanopsinMR/logs -o /data/jag/MELA/MelanopsinMR/logs /data/jag/MELA/MelanopsinMR/fixSubsASO-03.sh
qsub -l h_vmem=50.2G,s_vmem=50G -e /data/jag/MELA/MelanopsinMR/logs -o /data/jag/MELA/MelanopsinMR/logs /data/jag/MELA/MelanopsinMR/fixSubsASO-04.sh
qsub -l h_vmem=50.2G,s_vmem=50G -e /data/jag/MELA/MelanopsinMR/logs -o /data/jag/MELA/MelanopsinMR/logs /data/jag/MELA/MelanopsinMR/fixSubsASO-05.sh