%% Set up parameters
session_dir = '/data/jag/MELA/HERO_gka1/033116';
subject_name =  'HERO_gka1_3T';
subj_name = 'HERO_gka1';
dropbox_dir = '/Users/giulia/Dropbox (Aguirre-Brainard Lab)/MELA_analysis/MelanopsinMR/MelPulses_400%/HERO_gka1/033116';
SUBJECTS_DIR = '/data/jag/MELA/freesurfer_subjects';
copeNames = {...
    'Sec00' ...
    'Sec01' ...
    'Sec02' ...
    'Sec03' ...
    'Sec04' ...
    'Sec05' ...
    'Sec06' ...
    'Sec07' ...
    'Sec08' ...
    'Sec09' ...
    'Sec10' ...
    'Sec11' ...
    'Sec12' ...
    'Sec13' ...
    };
hemis = {...
    'mh'...
    'lh'...
    'rh'...
    };
ROIs = {...
    'V1' ...
    'V2andV3'...
    'LGN'...
    %         'V1all'...
    %         'V1low'...
    %         'V1mid'...
    %         'V1high'...
    };

funcs = {...
    'FIR_raw' ...
    % 'FIR_5mm'...
    };
funcNames = {...
    'FIR.raw' ...
    % 'FIR.5mm'...
    };

Conditions = {'MaxMelPulse'};
Runs = {[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]};

% %% Project the copes (execute if copes have not been projected yet)
% project_copes(session_dir, subject_name, dropbox_dir, SUBJECTS_DIR, ...
%     copeNames, hemis, ROIs, funcs, funcNames, Conditions, Runs, false);

%% Plot the FIR
FIR_assemble(session_dir, subject_name, subj_name, dropbox_dir, SUBJECTS_DIR, ...
    copeNames, hemis, ROIs, funcs, funcNames, Conditions, Runs);