%% define template directory and path
templateDir = '/data/jag/MELA/Matlab/MelanopsinMR/FEAT_templates';
templateName = 'MaxMelCRF';

%% set number of contrasts and 
EVs_number = 84;

Contrasts_number = 84;
Ftests_number = 6;


%% create static parameters for the fsf file (fsf struct)
% Note that this struct does not need to be modified
condition = 'MelanopsinMR';
fsf = create_fsf_struct (EVs_number, Contrasts_number, Ftests_number, condition, templateDir, templateName);

%% create blank contrasts, ftests and EV structs
condition = 'blank';

[Contrasts, Ftests] = create_CandF_struct (Contrasts_number,Ftests_number,condition,templateDir,templateName);
EVs = create_EVs_struct (EVs_number,condition,templateDir, templateName);

%% fill in the structs properly
% EVs
EVs.shape(1:end) = 3;

EV_names = {...
    'Mel_025Pct_delta_00Sec' ...
    'Mel_025Pct_delta_01Sec' ...
    'Mel_025Pct_delta_02Sec' ...
    'Mel_025Pct_delta_03Sec' ...
    'Mel_025Pct_delta_04Sec' ...
    'Mel_025Pct_delta_05Sec' ...
    'Mel_025Pct_delta_06Sec' ...
    'Mel_025Pct_delta_07Sec' ...
    'Mel_025Pct_delta_08Sec' ...
    'Mel_025Pct_delta_09Sec' ...
    'Mel_025Pct_delta_10Sec' ...
    'Mel_025Pct_delta_11Sec' ...
    'Mel_025Pct_delta_12Sec' ...
    'Mel_025Pct_delta_13Sec' ...
    'Mel_050Pct_delta_00Sec' ...
    'Mel_050Pct_delta_01Sec' ...
    'Mel_050Pct_delta_02Sec' ...
    'Mel_050Pct_delta_03Sec' ...
    'Mel_050Pct_delta_04Sec' ...
    'Mel_050Pct_delta_05Sec' ...
    'Mel_050Pct_delta_06Sec' ...
    'Mel_050Pct_delta_07Sec' ...
    'Mel_050Pct_delta_08Sec' ...
    'Mel_050Pct_delta_09Sec' ...
    'Mel_050Pct_delta_10Sec' ...
    'Mel_050Pct_delta_11Sec' ...
    'Mel_050Pct_delta_12Sec' ...
    'Mel_050Pct_delta_13Sec' ...
    'Mel_100Pct_delta_00Sec' ...
    'Mel_100Pct_delta_01Sec' ...
    'Mel_100Pct_delta_02Sec' ...
    'Mel_100Pct_delta_03Sec' ...
    'Mel_100Pct_delta_04Sec' ...
    'Mel_100Pct_delta_05Sec' ...
    'Mel_100Pct_delta_06Sec' ...
    'Mel_100Pct_delta_07Sec' ...
    'Mel_100Pct_delta_08Sec' ...
    'Mel_100Pct_delta_09Sec' ...
    'Mel_100Pct_delta_10Sec' ...
    'Mel_100Pct_delta_11Sec' ...
    'Mel_100Pct_delta_12Sec' ...
    'Mel_100Pct_delta_13Sec' ...
    'Mel_200Pct_delta_00Sec' ...
    'Mel_200Pct_delta_01Sec' ...
    'Mel_200Pct_delta_02Sec' ...
    'Mel_200Pct_delta_03Sec' ...
    'Mel_200Pct_delta_04Sec' ...
    'Mel_200Pct_delta_05Sec' ...
    'Mel_200Pct_delta_06Sec' ...
    'Mel_200Pct_delta_07Sec' ...
    'Mel_200Pct_delta_08Sec' ...
    'Mel_200Pct_delta_09Sec' ...
    'Mel_200Pct_delta_10Sec' ...
    'Mel_200Pct_delta_11Sec' ...
    'Mel_200Pct_delta_12Sec' ...
    'Mel_200Pct_delta_13Sec' ...
    'Mel_400Pct_delta_00Sec' ...
    'Mel_400Pct_delta_01Sec' ...
    'Mel_400Pct_delta_02Sec' ...
    'Mel_400Pct_delta_03Sec' ...
    'Mel_400Pct_delta_04Sec' ...
    'Mel_400Pct_delta_05Sec' ...
    'Mel_400Pct_delta_06Sec' ...
    'Mel_400Pct_delta_07Sec' ...
    'Mel_400Pct_delta_08Sec' ...
    'Mel_400Pct_delta_09Sec' ...
    'Mel_400Pct_delta_10Sec' ...
    'Mel_400Pct_delta_11Sec' ...
    'Mel_400Pct_delta_12Sec' ...
    'Mel_400Pct_delta_13Sec' ...
    'Mel_AttentionTask_delta_00Sec' ...
    'Mel_AttentionTask_delta_01Sec' ...
    'Mel_AttentionTask_delta_02Sec' ...
    'Mel_AttentionTask_delta_03Sec' ...
    'Mel_AttentionTask_delta_04Sec' ...
    'Mel_AttentionTask_delta_05Sec' ...
    'Mel_AttentionTask_delta_06Sec' ...
    'Mel_AttentionTask_delta_07Sec' ...
    'Mel_AttentionTask_delta_08Sec' ...
    'Mel_AttentionTask_delta_09Sec' ...
    'Mel_AttentionTask_delta_10Sec' ...
    'Mel_AttentionTask_delta_11Sec' ...
    'Mel_AttentionTask_delta_12Sec' ...
    'Mel_AttentionTask_delta_13Sec' ...
    };
for nn = 1: length(EV_names)
    EVs.title{nn} = EV_names{nn};
end

% contrasts
Contrasts.conpic_real(1:end) = 1;
Contrasts.conpic_orig(1:end) = 1;
Contrasts.con_real = eye(84,84);
Contrasts.con_orig = eye(84,84);
for nn = 1: length(EV_names)
    Contrasts.conname_orig{nn} = EV_names{nn};
    Contrasts.conname_real{nn} = EV_names{nn};
end

% Ftests
Ftests.ftest_real(1,(1:14)) = 1;
Ftests.ftest_real(2,(15:28)) = 1;
Ftests.ftest_real(3,(29:42)) = 1;
Ftests.ftest_real(4,(43:56)) = 1;
Ftests.ftest_real(5,(57:70)) = 1;
Ftests.ftest_real(6,(71:84)) = 1;


%%  save out the modified struct (this overwrites the previously blank ones)
save(fullfile(templateDir, [templateName '_Contrasts.mat']), 'Contrasts');
save(fullfile(templateDir, [templateName '_Ftests.mat']), 'Ftests');



%% write the fsf template
% note that this still needs to be filled with file paths for every bold
% run.
write_fsf_template (templateDir,templateName, fsf, EVs, Contrasts, Ftests)



