%%
output_dir = '/Users/giulia/Desktop/TEST'%'/Users/giulia/Dropbox-Aguirre-Brainard-Lab/MELA_analysis/MelanopsinMR/FIR_comparisons';
data_dir = '/data/jag/MELA/MelanopsinMR';
subjNames = { ...
    'HERO_asb1' ...
    'HERO_aso1' ...
    'HERO_gka1' ...
    'HERO_mxs1' ...
    };
sessionsMEL = { ...
    '032416' ...
    '032516' ...
    '033116' ...
    '040616' ...
    };
sessionsLMS = { ...
    '040716' ...
    '033016' ...
    '040116' ...
    '040816' ...
    };
sessionsCTRL = { ...
    '051016' ...
    '042916' ...
    '050616' ...
    '050916' ...
    };

hemis = {...
    'mh'...
    'lh'...
    'rh'...
    };
ROIs = {...
    'V1' ...
    'V2andV3'...
    'LGN'...
    };
for ss = 1:length(subjNames)
    subjName = subjNames{ss};
    for hh = 1:length(hemis)
        hemi = hemis{hh};
        for jj = 1:length(ROIs)
            ROI = ROIs{jj};
            dataMEL = fullfile (data_dir, subjName, sessionsMEL{ss}, 'CSV_datafiles', [subjName '_' 'MelPulses_400pct_' hemi '_' ROI '_wdrf.tf_mean.csv']);
            dataLMS = fullfile (data_dir, subjName, sessionsLMS{ss}, 'CSV_datafiles', [subjName '_' 'LMSPulses_400pct_' hemi '_' ROI '_wdrf.tf_mean.csv']);
            dataCTRL = fullfile (data_dir, subjName, sessionsCTRL{ss}, 'CSV_datafiles', [subjName '_' 'SplatterControl_100pct_' hemi '_' ROI '_wdrf.tf_mean.csv']);
            
            dataFiles = {...
                dataMEL ...
                dataLMS ...
                dataCTRL
                };
            
            errorMEL = fullfile (data_dir, subjName, sessionsMEL{ss}, 'CSV_datafiles', [subjName '_' 'MelPulses_400pct_' hemi '_' ROI '_wdrf.tf_SEM.csv']);
            errorLMS = fullfile (data_dir, subjName, sessionsLMS{ss}, 'CSV_datafiles', [subjName '_' 'LMSPulses_400pct_' hemi '_' ROI '_wdrf.tf_SEM.csv']);
            errorCTRL = fullfile (data_dir, subjName, sessionsCTRL{ss}, 'CSV_datafiles', [subjName '_' 'SplatterControl_100pct_' hemi '_' ROI '_wdrf.tf_SEM.csv']);
            
            errorFiles = {...
                errorMEL ...
                errorLMS ...
                errorCTRL
                };
            
            dataExt = 'csv' ;
            legendTexts = { ...
                '400% Melanopsin Pulse' ...
                '400% LMS Pulse' ...
                '195% SplatterControl'
                };
            titleText = [subjName ' Mel LMS Control ' hemi ' ' ROI];
            saveName = [subjName '_MEL_LMS_CTRL_100' hemi '_' ROI] ;
            
            FIR_multiplot (output_dir,dataFiles, dataExt, legendTexts, titleText, saveName)
        end
    end
end