dropbox_dir ='/Users/giulia/Dropbox-Aguirre-Brainard-Lab/MELA_analysis/MelanopsinMR/FIR_comparisons';
data_dir = '/data/jag/MELA/MelanopsinMR';
conditions = {...
    'MelPulses_400pct' ...
    'LMSPulses_400pct' ...
    };
subjNames = { ...
    'HERO_asb1' ...
    'HERO_aso1' ...
    'HERO_gka1' ...
    'HERO_mxs1' ...
    };
sessionsMEL = { ...
    '032416' ...
    '032516' ...
    '033116' ...
    '040616' ...
    };
sessionsLMS = { ...
    '040716' ...
    '033016' ...
    '040116' ...
    '040816' ...
    };

hemis = {...
    'mh'...
    'lh'...
    'rh'...
    };
ROIs = {...
    'V1' ...
    'V2andV3'...
    'LGN'...
    };
for cc = 1:length(conditions)
    condition = conditions{cc};
    for hh = 1:length(hemis)
        hemi = hemis{hh};
        for jj = 1:length(ROIs)
            ROI = ROIs{jj};
            for ss = 1:length(subjNames)
                if cc == 1
                    sessions = sessionsMEL;
                elseif cc == 2
                    sessions = sessionsLMS;
                end
                dataFiles{ss} = fullfile (data_dir, subjNames{ss}, sessions{ss}, 'CSV_datafiles', [subjNames{ss} '_' condition '_' hemi '_' ROI '_wdrf.tf_mean.csv']);
                dataExt = 'csv' ;
                legendTexts = subjNames;
                titleText = [ 'Across subject ' condition ' response for ' hemi ' ' ROI];
                saveName = ['Across_subject_' condition '_' hemi '_' ROI] ;
                
                output_dir = fullfile (dropbox_dir, 'Across_subjects');
                if ~exist ('output_dir', 'dir')
                    mkdir ('output_dir')
                end
            end
            FIR_multiplot (output_dir,dataFiles, dataExt, legendTexts, titleText, saveName)
        end
    end
end