dropbox_dir = '/Users/giulia/Desktop/TEST' %'/Users/giulia/Dropbox-Aguirre-Brainard-Lab/MELA_analysis/MelanopsinMR/FIR_comparisons';
data_dir = '/data/jag/MELA/MelanopsinMR';
subjNames = { ...
%     'HERO_asb1' ...
%     'HERO_aso1' ...
%     'HERO_gka1' ...
    'HERO_mxs1' ...
    };

sessions = { ...
%     '051016' ...
%     '042916' ...
%     '050616' ...
    '050916' ...
    };
conditions = {...
    'SplatterControl_25pct'...
    'SplatterControl_50pct'...
    'SplatterControl_100pct'...
    'SplatterControl_195pct'...
%     'SplatterControl_AttentionTask'...
    };

hemis = {...
    'mh'...
    'lh'...
    'rh'...
    };
ROIs = {...
    'V1' ...
    'V2andV3'...
    'LGN'...
    };
for ss = 1:length(subjNames)
    for hh = 1:length(hemis)
        hemi = hemis{hh};
        for jj = 1:length(ROIs)
            ROI = ROIs{jj};
            for cc = 1:length(conditions)
                condition = conditions{cc};
                dataFiles{cc} = fullfile (data_dir, subjNames{ss}, sessions{ss}, 'CSV_datafiles', [subjNames{ss} '_' condition '_' hemi '_' ROI '_wdrf.tf_mean.csv']);
                dataExt = 'csv' ;
                legendTexts = conditions;
                titleText = [ subjNames{ss} ' - Splatter Control - '  hemi ' '  ROI];
                saveName = [subjNames{ss} '_SplatterControl_ALL' '_' hemi '_' ROI] ;
                output_dir = fullfile (dropbox_dir, 'SplatterControl', subjNames{ss}, sessions {ss} );
                if ~exist ('output_dir', 'dir')
                    mkdir ('output_dir')
                end
            end
            FIR_multiplot (output_dir,dataFiles, dataExt, legendTexts, titleText, saveName)
        end
    end
end