dropbox_dir ='/Users/giulia/Dropbox-Aguirre-Brainard-Lab/MELA_analysis/MelanopsinMR/FIR_comparisons';
data_dir = '/data/jag/MELA/MelanopsinMR';
conditions = {...
    'MelPulses_400pct' ...
    'LMSPulses_400pct' ...
    };
subjNames = { ...
    'HERO_asb1' ...
    'HERO_aso1' ...
    'HERO_gka1' ...
    'HERO_mxs1' ...
    };
sessionsMEL = { ...
    '032416' ...
    '032516' ...
    '033116' ...
    '040616' ...
    };
sessionsLMS = { ...
    '040716' ...
    '033016' ...
    '040116' ...
    '040816' ...
    };

hemis = {...
    'mh'...
    'lh'...
    'rh'...
    };
ROIs = {...
    'V1' ...
    'V2andV3'...
    'LGN'...
    };
for cc = 1:length(conditions)
    condition = conditions{cc};
    for ss = 1:length(subjNames)
        subjName = subjNames{ss};
        for hh = 1:length(hemis)
            hemi = hemis{hh};
            for jj = 1:length(ROIs)
                ROI = ROIs{jj};
                if cc == 1
                    sessions = sessionsMEL;
                elseif cc == 2
                    sessions = sessionsLMS;
                end
                data = fullfile (data_dir, subjName, sessions{ss}, 'CSV_datafiles', [subjName '_' condition '_' hemi '_' ROI '_wdrf.tf_mean.csv']);
                attTask = fullfile (data_dir, subjName, sessions{ss}, 'CSV_datafiles', [subjName '_' condition '_AttentionTask_' hemi '_' ROI '_wdrf.tf_mean.csv']);
                
                dataFiles = {...
                    data ...
                    attTask ...
                    };
                
                dataExt = 'csv' ;
                legendTexts = { ...
                    condition ...
                    'AttentionTask' ...
                    };
                titleText = [subjName ' ' condition ' and attention task ' hemi ' ' ROI];
                saveName = [subjName '_' condition '_and_AT_' hemi '_' ROI] ;
                
                output_dir = fullfile (dropbox_dir, 'Stimuli_and_Task');
                if ~exist ('output_dir', 'dir')
                    mkdir ('output_dir')
                end
                
                FIR_multiplot (output_dir,dataFiles, dataExt, legendTexts, titleText, saveName)
            end
        end
    end
end