%% set saving path and variables
dropbox_dir = '/Users/giulia/Desktop/Results_Round2' %'/Users/giulia/Dropbox-Aguirre-Brainard-Lab/MELA_analysis/MelanopsinMR/FIR_comparisons';
data_dir = '/data/jag/MELA/MelanopsinMR/Results';

subjNames = { ...
    'HERO_asb1' ...
    'HERO_aso1' ...
    'HERO_gka1' ...
    'HERO_mxs1' ...
    };

sessionsMEL = { ...
    '032416' ...
    '032516' ...
    '033116' ...
    '040616' ...
    };
sessionsLMS = { ...
    '040716' ...
    '033016' ...
    '040116' ...
    '040816' ...
    };
sessionsCTRL = { ...
    '051016' ...
    '042916' ...
    '050616' ...
    '050916' ...
    };
sessionsMELCRF = { ...
    '060716' ...
    '053116' ...
    '060216' ...
    '060916' ...
    };
sessionsLMSCRF = { ...
    '060816' ...
    '060116' ...
    '060616' ...
    '062816' ...
    };

conditions = {...
    'MelPulses_400pct' ...
    'LMSPulses_400pct' ...
    'SplatterControl' ...
    'MaxMelCRF' ...
    'MaxLMSCRF' ...
    };

controlsSplatter = { ...
    '_25pct'...
    '_50pct'...
    '_100pct'...
    '_195pct'...
    '_AttentionTask'...
    };

controlsCRF = {...
    '_25pct'...
    '_50pct'...
    '_100pct'...
    '_200pct'...
    '_400pct'...
    '_AttentionTask'...
    };

directions = { ...
    'Mel'
    'LMS'
    'AttentionTask'
    };

hemis = {...
    'mh'...
    };
ROIs = {...
    'V1' ...
    'V2andV3'...
    };


%% make 3 column files for all data
for ss = 1:length(subjNames)
    subjName = subjNames{ss};
    for cc = 1:length(conditions)
        condition = conditions{cc};
        switch (condition)
            case 'MelPulses_400pct'
                sessions = sessionsMEL;
                controls = { ...
                    '' ...
                    '_AttentionTask' ...
                    };
                conditionFolder =  'MaxMel_400%';
            case 'LMSPulses_400pct'
                sessions = sessionsLMS;
                controls = { ...
                    '' ...
                    '_AttentionTask' ...
                    };
                conditionFolder =  'MaxLMS_400%';
                
            case 'SplatterControl'
                sessions = sessionsCTRL;
                controls = controlsSplatter;
                conditionFolder =  'SplatterControl_CRF';
                
            case 'MaxMelCRF'
                sessions = sessionsMELCRF;
                controls = controlsCRF;
                conditionFolder = 'MaxMel_CRF';
                
            case 'MaxLMSCRF'
                sessions = sessionsLMSCRF;
                controls = controlsCRF;
                conditionFolder = 'MaxLMS_CRF';
                
            otherwise
                error ('No condition selected')
        end
        session = sessions{ss};
        for hh = 1:length(hemis)
            hemi = hemis{hh};
            for jj = 1:length(ROIs)
                ROI = ROIs{jj};
                for kk = 1:length(controls)
                    control = controls{kk};
                    
                    meanFile = fullfile (data_dir, condition, subjName, session, 'CSV_datafiles', [subjName '_' condition control '_' hemi '_' ROI '_wdrf.tf_mean.csv']);
                    semFile = fullfile (data_dir, condition, subjName, session, 'CSV_datafiles', [subjName '_' condition control '_' hemi '_' ROI '_wdrf.tf_SEM.csv']);
                    saveFile = fullfile (dropbox_dir, subjName, 'bySession', conditionFolder, [subjName '_' condition control '_' hemi '_' ROI]);
                    
                    % zero center each mean value (offset correction)
                    meanRaw = csvread(meanFile);
                    mean = meanRaw - meanRaw(1);
                    
                    % make a 3 column file with t, mean, SEM
                    time = 0:13;
                    SEM = csvread(semFile);
                    
                    M = [ time ; mean ; SEM]';
                    save (saveFile, 'M')
                end
            end
        end
    end
end






% plot all MEL stimuli (from 3 column file)


% plot all LMS stimuli (from 3 column file)


% plot all attention tasks




%% AVERAGE