%% Set up parameters
session_dir = '/data/jag/MELA/HERO_aso1/033016';
subject_name =  'HERO_aso1_MaxMel';
subj_name = 'HERO_aso1';
dropbox_dir = '/Users/giulia/Dropbox (Aguirre-Brainard Lab)/MELA_analysis/MelanopsinMR/LMSPulses_400%/HERO_aso1/033016';
SUBJECTS_DIR = '/data/jag/MELA/freesurfer_subjects';
copeNames = {...
    'Sec00' ...
    'Sec01' ...
    'Sec02' ...
    'Sec03' ...
    'Sec04' ...
    'Sec05' ...
    'Sec06' ...
    'Sec07' ...
    'Sec08' ...
    'Sec09' ...
    'Sec10' ...
    'Sec11' ...
    'Sec12' ...
    'Sec13' ...
    };
hemis = {...
    'mh'...
    'lh'...
    'rh'...
    };
ROIs = {...
    'V1' ...
    'V2andV3'...
    'LGN'...
    %         'V1all'...
    %         'V1low'...
    %         'V1mid'...
    %         'V1high'...
    };

funcs = {...
    'FIR_raw' ...
    % 'FIR_5mm'...
    };
funcNames = {...
    'FIR.raw' ...
    % 'FIR.5mm'...
    };

Conditions = {'MaxLMSPulse'};
Runs = {[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]};

%%
SaveMeanSEM(session_dir, subject_name, subj_name, dropbox_dir, SUBJECTS_DIR, copeNames, hemis, ROIs, funcs, funcNames, Conditions, Runs)

