function [figHandle]=fmriMaxMel_makeCRFResultFigure( deduFitData, subjectNameFunc)

figHandle=figure();
lmsCRFCells=deduFitData{1};
melCRFCells=deduFitData{2};
splatCRFCells=deduFitData{3};

contrastLabels={'25','50','100','200','400'};
splatterLabels={[char(188) 'x'], [char(189) 'x'],'1x','2x'};

nSubjects=4;

for ss=1:nSubjects
    subplotHandle=subplot(1,nSubjects,ss);
    
    % Plot the LMS CRF
    means=cellfun(@(x) x.meanAmplitude, lmsCRFCells);
    sems=cellfun(@(x) x.semAmplitude, lmsCRFCells);
        sems=sems(ss,:);
        means=means(ss,:);
    fmriMaxMel_PlotCRF( subplotHandle, [1, 2, 3, 4, 5], means, sems, ...
        'xTickLabels',contrastLabels,...
        'xlim',[0 7],...
        'lineColor',[.25 .25 .25],...
        'markerColor',[0 0 0],...
        'errorColor',[.5 .5 .5],...
        'plotTitle',subjectNameFunc(ss));
    hold on
    
    % Plot the Mel CRF
    means=cellfun(@(x) x.meanAmplitude, melCRFCells);
    sems=cellfun(@(x) x.semAmplitude, melCRFCells);
        means=means(ss,:);
        sems=sems(ss,:);
    fmriMaxMel_PlotCRF( subplotHandle, [1, 2, 3, 4, 5], means, sems, ...
        'xTickLabels',contrastLabels,...
        'xlim',[0 7],...
        'lineColor',[.25 .25 1],...
        'markerColor',[0 0 1],...
        'errorColor',[.5 .5 1],...
        'plotTitle',subjectNameFunc(ss));
    
    % Plot the splatter CRF
    means=cellfun(@(x) x.meanAmplitude, splatCRFCells);
    sems=cellfun(@(x) x.semAmplitude, splatCRFCells);
        means=means(ss,:);
        sems=sems(ss,:);
    fmriMaxMel_PlotCRF( subplotHandle, [3, 4, 5, 6], means, sems, ...
        'xTickLabels',splatterLabels,...
        'xlim',[0 7],...
        'lineColor',[1 .25 .25],...
        'markerColor',[1 0 0],...
        'errorColor',[1 .5 .5],...
        'plotTitle',subjectNameFunc(ss),...
        'xLabel','splatter',...
    'secondAxis',true);
    
    
end % subjects


end

