function [figHandle]=fmriMaxMel_makeCRFResultFigure( deduFitData, subjectNameFunc, fieldNameToPlot)

switch fieldNameToPlot
    case 'amplitude'
        meanField='meanAmplitude';
        semField='semAmplitude';
        yLabel='% BOLD change';
        yLimVals=[-0.5 1];
    case 'duration'
        meanField='meanDuration';
        semField='semDuration';
        yLabel='duration [secs]';
        yLimVals=[-1 8];
    otherwise
        error('That is not an available field name to plot');
end

figHandle=figure();
lmsCRFCells=deduFitData{1};
melCRFCells=deduFitData{2};
splatCRFCells=deduFitData{3};
lms400Cells=deduFitData{4};
mel400Cells=deduFitData{5};

contrastLabels={'25','50','100','200','400'};
splatterLabels={[char(188) 'x'], [char(189) 'x'],'1x','2x'};

nSubjects=4;
nExperiments=5;

% The extra "subject" will hold the across-subject average
for ss=1:nSubjects+1
    
    subplotHandle=subplot(2,nSubjects,ss);
    
    for ee=nExperiments:-1:1
        
        meanAllSubs=cellfun(@(x) x.(meanField), deduFitData{ee});
        semsAllSubs=cellfun(@(x) x.(semField), deduFitData{ee});
        
        if ss==nSubjects+1
            means=squeeze(mean(meanAllSubs,1));
            sems=squeeze(std(meanAllSubs,1))/sqrt(nSubjects);
            subjectName='Subject mean';
        else
            means=meanAllSubs(ss,:);
            sems=semsAllSubs(ss,:);
            subjectName=subjectNameFunc(ss);
        end
        
        switch ee
            case 1 % The LMS CRF
                fmriMaxMel_PlotCRF( subplotHandle, [1, 2, 3, 4, 5], means, sems, ...
                    'xTickLabels',contrastLabels,...
                    'xlim',[0 7],...
                    'ylim',yLimVals,...
                    'yLabel',yLabel,...
                    'lineColor',[.25 .25 .25],...
                    'markerColor',[0 0 0],...
                    'errorColor',[.5 .5 .5],...
                    'plotTitle','');
                hold on
            case 2 % The Mel CRF
                fmriMaxMel_PlotCRF( subplotHandle, [1, 2, 3, 4, 5], means, sems, ...
                    'xTickLabels',contrastLabels,...
                    'xlim',[0 7],...
                    'ylim',yLimVals,...
                    'yLabel',yLabel,...
                    'lineColor',[.25 .25 1],...
                    'markerColor',[0 0 1],...
                    'errorColor',[.5 .5 1],...
                    'plotTitle','');
                hold on
                subjectMelMeans=means; % retain this for the shift calc below
            case 3 % The splatter CRF
                fmriMaxMel_PlotCRF( subplotHandle, [3, 4, 5, 6], means, sems, ...
                    'xTickLabels',splatterLabels,...
                    'xlim',[0 7],...
                    'ylim',yLimVals,...
                    'yLabel',yLabel,...
                    'lineColor',[0.25 1 .25],...
                    'markerColor',[0 1 0],...
                    'errorColor',[.5 1 .5],...
                    'plotTitle','',...
                    'xLabel','splatter',...
                    'secondAxis',true);
                hold on
                subjectSplatMeans=means; % retain this for the shift calc below
            case 4 % The single LMS 400% trial experiment
                fmriMaxMel_PlotCRF( subplotHandle, [5], means, sems, ...
                    'xTickLabels',{'400'},...
                    'xlim',[0 7],...
                    'ylim',yLimVals,...
                    'yLabel',yLabel,...
                    'lineColor',[.25 .25 .25],...
                    'markerColor',[0 0 0],...
                    'errorColor',[.5 .5 .5],...
                    'plotSymbol','p',...
                    'plotTitle','');
                hold on
            case 5 % The single Mel 400% trial experiment
                fmriMaxMel_PlotCRF( subplotHandle, [5], means, sems, ...
                    'xTickLabels',{'400'},...
                    'xlim',[0 7],...
                    'ylim',yLimVals,...
                    'yLabel',yLabel,...
                    'lineColor',[.25 .25 1],...
                    'markerColor',[0 0 1],...
                    'errorColor',[.5 .5 1],...
                    'plotSymbol','p',...
                    'plotTitle','');
                hold on
        end % switch on the experient type
    end % loop over experiment types
    
    % Calculate the multiplier required to shift the splatter CRF to best
    % fit the melanopsin CRF
    interpMel=interp1(-log(2)*5:log(2):-log(2),subjectMelMeans,-log(2)*5:log(2)/100:-log(2));
    interpMel=[interpMel nan(1,100)];
    interpSplat=interp1(-log(2)*3:log(2):0,subjectSplatMeans,-log(2)*3:log(2)/100:0);
    interpSplat=[nan(1,100) nan(1,100) interpSplat];
    interpX=-log(2)*5:log(2)/100:0;
    for shifter=1:600
        r(shifter)=sqrt(nansum((interpMel-circshift(interpSplat,-1*shifter)).^2))/sum(~isnan((interpMel-circshift(interpSplat,-1*shifter))));
    end
    idx=find(r==min(r));
    splatShift=1/exp(interpX(end-idx));
    title(subplotHandle,[subjectName ' splat x' num2str(splatShift,'%.3g')],'Interpreter', 'none');
    
end % subjects

end % function

