function [figHandle]=fmriMaxMel_makeCRFResultFigure( deduFitData, subjectNameFunc, fieldNameToPlot)

switch fieldNameToPlot
    case 'amplitude'
        meanField='meanAmplitude';
        semField='semAmplitude';
        yLabel='% BOLD change';
        yLimVals=[-0.5 1];
    case 'duration'
        meanField='meanDuration';
        semField='semDuration';
        yLabel='duration [secs]';
        yLimVals=[-1 8];
    otherwise
        error('That is not an available field name to plot');
end

figHandle=figure();
lmsCRFCells=deduFitData{1};
melCRFCells=deduFitData{2};
splatCRFCells=deduFitData{3};
lms400Cells=deduFitData{4};
mel400Cells=deduFitData{5};

contrastLabels={'25','50','100','200','400'};
splatterLabels={[char(188) 'x'], [char(189) 'x'],'1x','2x'};

nSubjects=4;

for ss=1:nSubjects
    subplotHandle=subplot(1,nSubjects,ss);
    
    % Plot the single LMS 400% experiment point
    mean400LMS=cellfun(@(x) x.(meanField), lms400Cells);
    sems400LMS=cellfun(@(x) x.(semField), lms400Cells);
    sems=sems400LMS(ss,:);
    means=mean400LMS(ss,:);
    fmriMaxMel_PlotCRF( subplotHandle, [5], means, sems, ...
        'xTickLabels',{'400'},...
        'xlim',[0 7],...
        'ylim',yLimVals,...
        'yLabel',yLabel,...
        'lineColor',[.25 .25 .25],...
        'markerColor',[0 0 0],...
        'errorColor',[.5 .5 .5],...
        'plotSymbol','p',...
        'plotTitle',subjectNameFunc(ss));
    hold on
    
    % Plot the single Mel 400% experiment point
    mean400Mel=cellfun(@(x) x.(meanField), mel400Cells);
    sems400Mel=cellfun(@(x) x.(semField), mel400Cells);
    sems=sems400Mel(ss,:);
    means=mean400Mel(ss,:);
    fmriMaxMel_PlotCRF( subplotHandle, [5], means, sems, ...
        'xTickLabels',{'400'},...
        'xlim',[0 7],...
        'ylim',yLimVals,...
        'yLabel',yLabel,...
        'lineColor',[.25 .25 1],...
        'markerColor',[0 0 1],...
        'errorColor',[.5 .5 1],...
        'plotSymbol','p',...
        'plotTitle',subjectNameFunc(ss));
    
    % Plot the LMS CRF
    meansLMS=cellfun(@(x) x.(meanField), lmsCRFCells);
    semsLMS=cellfun(@(x) x.(semField), lmsCRFCells);
    sems=semsLMS(ss,:);
    means=meansLMS(ss,:);
    fmriMaxMel_PlotCRF( subplotHandle, [1, 2, 3, 4, 5], means, sems, ...
        'xTickLabels',contrastLabels,...
        'xlim',[0 7],...
        'ylim',yLimVals,...
        'yLabel',yLabel,...
        'lineColor',[.25 .25 .25],...
        'markerColor',[0 0 0],...
        'errorColor',[.5 .5 .5],...
        'plotTitle',subjectNameFunc(ss));
    
    % Plot the Mel CRF
    meansMel=cellfun(@(x) x.(meanField), melCRFCells);
    semsMel=cellfun(@(x) x.(semField), melCRFCells);
    means=meansMel(ss,:);
    sems=semsMel(ss,:);
    fmriMaxMel_PlotCRF( subplotHandle, [1, 2, 3, 4, 5], means, sems, ...
        'xTickLabels',contrastLabels,...
        'xlim',[0 7],...
        'ylim',yLimVals,...
        'yLabel',yLabel,...
        'lineColor',[.25 .25 1],...
        'markerColor',[0 0 1],...
        'errorColor',[.5 .5 1],...
        'plotTitle',subjectNameFunc(ss));
    
    % Plot the splatter CRF
    meansSplat=cellfun(@(x) x.(meanField), splatCRFCells);
    semsSplat=cellfun(@(x) x.(semField), splatCRFCells);
    means=meansSplat(ss,:);
    sems=semsSplat(ss,:);
    fmriMaxMel_PlotCRF( subplotHandle, [3, 4, 5, 6], means, sems, ...
        'xTickLabels',splatterLabels,...
        'xlim',[0 7],...
        'ylim',yLimVals,...
        'yLabel',yLabel,...
        'lineColor',[0.25 1 .25],...
        'markerColor',[0 1 0],...
        'errorColor',[.5 1 .5],...
        'plotTitle',subjectNameFunc(ss),...
        'xLabel','splatter',...
        'secondAxis',true);
    
    % Calculate the multiplier required to shift the splatter CRF to best
    % fit the melanopsin CRF
    interpMel=interp1(-log(2)*5:log(2):-log(2),meansMel(ss,:),-log(2)*5:log(2)/100:-log(2));
    interpMel=[interpMel nan(1,100)];
    interpSplat=interp1(-log(2)*3:log(2):0,meansSplat(ss,:),-log(2)*3:log(2)/100:0);
    interpSplat=[nan(1,100) nan(1,100) interpSplat];
    interpX=-log(2)*5:log(2)/100:0;
    for shifter=1:600
        r(shifter)=sqrt(nansum((interpMel-circshift(interpSplat,-1*shifter)).^2))/sum(~isnan((interpMel-circshift(interpSplat,-1*shifter))));
    end
    idx=find(r==min(r));
    splatShift=1/exp(interpX(end-idx));
    title(subplotHandle,[subjectNameFunc(ss) ' splat x' num2str(splatShift,'%.3g')],'Interpreter', 'none');
    
end % subjects


end

